{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bybutter",
    "module": "router-plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "router-plugin-1.0.0.jar",
          "url": "router-plugin-1.0.0.jar",
          "size": 18124,
          "sha512": "89233c98b4a4255245f5f47107053eb456f38700d3ee35b05402755b6c9b2c777d8698ac78ffed6f5138a6969523fdc911ff7532d01d1486124f8183dd7a7cea",
          "sha256": "cb95bf893c8ccfd2f45457ee4d77bf5ee6ae293ab96a62ba2df38544253f559e",
          "sha1": "bbf6373cfe207a236f33da6002152b743c85accf",
          "md5": "9ba566f7255ea6f7cdd9df827ee2af8c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "router-plugin-1.0.0.jar",
          "url": "router-plugin-1.0.0.jar",
          "size": 18124,
          "sha512": "89233c98b4a4255245f5f47107053eb456f38700d3ee35b05402755b6c9b2c777d8698ac78ffed6f5138a6969523fdc911ff7532d01d1486124f8183dd7a7cea",
          "sha256": "cb95bf893c8ccfd2f45457ee4d77bf5ee6ae293ab96a62ba2df38544253f559e",
          "sha1": "bbf6373cfe207a236f33da6002152b743c85accf",
          "md5": "9ba566f7255ea6f7cdd9df827ee2af8c"
        }
      ]
    }
  ]
}
