{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bybutter",
    "module": "router-plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "router-plugin-1.0.0.jar",
          "url": "router-plugin-1.0.0.jar",
          "size": 18124,
          "sha512": "465c62ac366b3fb2613e42e18e616d93889fa40caf03277c5dfc389e9a1a656ea5cb1b2758cdcc40ef24136de992d7335d4a12889f3e47a6addc0becdc03d313",
          "sha256": "62bcfbae2abed95a4389d7779ffd9346e75fbc285fadbb5c09393fd19d1cab1a",
          "sha1": "9e9cb339a4f16b1d3c1c931a4dc07843926c9055",
          "md5": "073db5c36fecf4b28a6bd3f711fef002"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "router-plugin-1.0.0.jar",
          "url": "router-plugin-1.0.0.jar",
          "size": 18124,
          "sha512": "465c62ac366b3fb2613e42e18e616d93889fa40caf03277c5dfc389e9a1a656ea5cb1b2758cdcc40ef24136de992d7335d4a12889f3e47a6addc0becdc03d313",
          "sha256": "62bcfbae2abed95a4389d7779ffd9346e75fbc285fadbb5c09393fd19d1cab1a",
          "sha1": "9e9cb339a4f16b1d3c1c931a4dc07843926c9055",
          "md5": "073db5c36fecf4b28a6bd3f711fef002"
        }
      ]
    }
  ]
}
