{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bybutter.router",
    "module": "router-plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "router-plugin-1.0.0.jar",
          "url": "router-plugin-1.0.0.jar",
          "size": 18124,
          "sha512": "483e2632aba7347675481b46ceb76b44ed42f365a948ad04f945977f8e31f0e82b425c9be3d8cf679ad2f48c9ba543066c92b8354e9f980aac56b0225222479a",
          "sha256": "572e96655ab10a1f308883120104521df2f3ebd3e93d18514460f0dcd2c5eb09",
          "sha1": "93d63337428dc67db5c8d98304822c6209810b90",
          "md5": "01b2aca313ae8c0ee9da9d22e1b9d819"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "router-plugin-1.0.0.jar",
          "url": "router-plugin-1.0.0.jar",
          "size": 18124,
          "sha512": "483e2632aba7347675481b46ceb76b44ed42f365a948ad04f945977f8e31f0e82b425c9be3d8cf679ad2f48c9ba543066c92b8354e9f980aac56b0225222479a",
          "sha256": "572e96655ab10a1f308883120104521df2f3ebd3e93d18514460f0dcd2c5eb09",
          "sha1": "93d63337428dc67db5c8d98304822c6209810b90",
          "md5": "01b2aca313ae8c0ee9da9d22e1b9d819"
        }
      ]
    }
  ]
}
